# python numpy learn

---


In [1]:
import numpy as np

---

## 1.attributes

In [2]:
a = np.array([2,23,4], dtype=np.int64)

In [3]:
print(a.ndim)
print(a.shape)
print(a.size)

1
(3,)
3


---

## 2.array

In [8]:
a = np.array([[2,23,4],[2,32,4]])
print(a.ndim)
print(a.shape)
print(a.size)

2
(2, 3)
6


In [6]:
a = np.arange(10, 20, 2)
print(a)

[10 12 14 16 18]


In [7]:
a = np.arange(12).reshape(3, 4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [9]:
a = np.linspace(1, 10, 5)
print(a)

[  1.     3.25   5.5    7.75  10.  ]


In [11]:
a = np.random.randn(2, 4)
print(a)

[[ 1.53580662  1.68912744  0.79103053  0.11843669]
 [-0.46768756  0.34718872  0.76420826  2.46176708]]


---

## 3.operation

In [12]:
b = a ** 2
print(b)

[[ 2.35870198  2.85315152  0.6257293   0.01402725]
 [ 0.21873166  0.12054001  0.58401427  6.06029715]]


In [13]:
c = 10 * np.sin(a)
print(c)

[[ 9.99387923  9.93007039  7.11078227  1.18159995]
 [-4.50823381  3.40255615  6.91965637  6.28657387]]


In [14]:
print(b < 3)

[[ True  True  True  True]
 [ True  True  True False]]


In [15]:
print(b == 3)

[[False False False False]
 [False False False False]]


In [17]:
c_dot = np.dot(a, b.T)
print(c_dot)

[[  8.93847896   1.71927162]
 [  0.40016576  15.30490059]]


In [18]:
c_dot_2 = a.dot(b.T)
print(c_dot_2)

[[  8.93847896   1.71927162]
 [  0.40016576  15.30490059]]


In [19]:
print(np.sum(a))

7.23987777938


In [20]:
print(np.sum(a, axis=1))

[ 4.13440128  3.1054765 ]


---

## 4.operation 2

In [23]:
print(a)

[[ 1.53580662  1.68912744  0.79103053  0.11843669]
 [-0.46768756  0.34718872  0.76420826  2.46176708]]


最小、大、均值索引：

In [21]:
print(np.argmax(a))

7


In [22]:
print(np.argmin(a))

4


In [26]:
print(np.mean(a))

0.904984722422


In [27]:
print(a.mean())

0.904984722422


中位数：

In [30]:
print(np.median(a))

0.77761939555


累加值：斐波那契：

In [31]:
print(np.cumsum(a))

[ 1.53580662  3.22493406  4.01596459  4.13440128  3.66671372  4.01390244
  4.7781107   7.23987778]


累差值(反向):

In [33]:
print(np.diff(a))

[[ 0.15332082 -0.89809692 -0.67259384]
 [ 0.81487628  0.41701955  1.69755881]]


非零值：

In [34]:
print(np.nonzero(a))

(array([0, 0, 0, 0, 1, 1, 1, 1], dtype=int64), array([0, 1, 2, 3, 0, 1, 2, 3], dtype=int64))


排序：

In [35]:
print(np.sort(a))

[[ 0.11843669  0.79103053  1.53580662  1.68912744]
 [-0.46768756  0.34718872  0.76420826  2.46176708]]


转置矩阵：

In [36]:
print(np.transpose(a))

[[ 1.53580662 -0.46768756]
 [ 1.68912744  0.34718872]
 [ 0.79103053  0.76420826]
 [ 0.11843669  2.46176708]]


In [37]:
print(a.T)

[[ 1.53580662 -0.46768756]
 [ 1.68912744  0.34718872]
 [ 0.79103053  0.76420826]
 [ 0.11843669  2.46176708]]


替换：

小于1的值替换为1，大于3的数替换为3：

In [39]:
print(np.clip(a, 1, 3))

[[ 1.53580662  1.68912744  1.          1.        ]
 [ 1.          1.          1.          2.46176708]]


行、列计算：

In [42]:
np.mean(a, axis=0)

array([ 0.53405953,  1.01815808,  0.7776194 ,  1.29010188])

In [43]:
np.mean(a, axis=1)

array([ 1.03360032,  0.77636912])

---

## 5.numpy的索引

In [44]:
a = np.arange(3, 15)
print(a)

[ 3  4  5  6  7  8  9 10 11 12 13 14]


索引行：

In [51]:
a = np.arange(3, 15).reshape((3, 4))
print(a)

[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]


In [47]:
print(a[2])

[11 12 13 14]


冒号代替所有数: 行、列、行里位置:

In [49]:
print(a[1, :])

[ 7  8  9 10]


In [50]:
print(a[:, 1])

[ 4  8 12]


In [52]:
print(a[1, 1:2])

[8]


行迭代：

In [53]:
for row in a:
    print(row)

[3 4 5 6]
[ 7  8  9 10]
[11 12 13 14]


转变成单行：

In [54]:
for item in a.flat:
    print(item)

3
4
5
6
7
8
9
10
11
12
13
14


---

## 6.numpy的array合并

上下合并：

In [57]:
A = np.array([1, 1, 1])
B = np.array([2, 2, 2])
C = np.vstack((A, B))
print(A.shape, B.shape, C.shape)

(3,) (3,) (2, 3)


左右合并：

In [56]:
D = np.hstack((A, B))
print(A.shape, B.shape, D.shape)

(3,) (3,) (6,)


序列转矩阵（转置）：

In [58]:
E = A[:, np.newaxis]
print(E)

[[1]
 [1]
 [1]]


In [59]:
A = np.array([1, 1, 1])[:, np.newaxis]
B = np.array([2, 2, 2])[:, np.newaxis]
print(np.hstack((A, A, B)))

[[1 1 2]
 [1 1 2]
 [1 1 2]]


多个合并：

In [60]:
C = np.concatenate((A, B, B, A), axis = 0)
print(C)

[[1]
 [1]
 [1]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [1]
 [1]
 [1]]


---

## 7.numpy的array分割

split只能等分：

列分割成两块：

In [61]:
A = np.arange(12).reshape((3,4))
B = np.split(A, 2, axis = 1)
print(B)

[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]


行分割成三块：

In [63]:
B = np.split(A, 3, axis=0)
print(B)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]


不等量分割：

In [64]:
B = np.split(A, 3, axis=1)

ValueError: array split does not result in an equal division

纵向分割：

In [65]:
B = np.vsplit(A, 3)
print(B)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]


横向分割：

In [66]:
B = np.hsplit(A, 2)
print(B)

[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]


---

## 8.numpy的copy、deep copy

关联:

In [67]:
a = np.arange(4)
b = a
c = a
d = b
a[0] = 11
d is a
d[1:3] = [22,33]

复制，不关联：

In [68]:
b = a.copy()
b[0] = 13

---


## 9.numpy.random

```
numpy.random.uniform(low,high,size)
```

功能：从一个均匀分布[low,high)中随机采样，注意定义域是左闭右开，即包含low，不包含high. size个数

```
numpy.random.randint(low, high=None, size=None, dtype='l')
```

Return random integers from low (inclusive) to high (exclusive).

```
numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)
```

在指定的间隔内返回均匀间隔的数字。返回num均匀分布的样本，在[start, stop]。

```
numpy.expand_dims
```

Expand the shape of an array.
Insert a new axis, corresponding to a given position in the array shape.

---

## 10.numpy.linalg.norm

数据归一化
返回Lx模，默认返回L2

---

## 11.numpy.mean

计算均值